import Head from 'next/head'
import {motion as mo} from "framer-motion"
import {container, element} from "../animate.js"


export default function Home() {
  return (
    <mo.div initial = {{y: "100%"}} animate = {{y : "0%"}} 
    transition = {{duration: 0.75, ease: "easeOut"}} exit = {{opaicty: 1}} className = "text-gray-900 absolute top-0 left-0 w-full bg-gradient-to-r from-blue-400 to-emerald-400 lg:px-30 px-10">
      <Head>
        <title>Page Transitions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        
          <div className='my-96 p-1'>
            <h1 className='p-1 text-5xl text-center lg:text-right lg:text-7xl'>Retail Happy</h1>
          </div>

          <div className='flex justify-between py-4'>

            <mo.div variants = {container} initial = "hidden" animate = "animated">

              <div className='overflow-hidden'>
                <mo.h2 variants={element} className="pb-2">Development</mo.h2>
              </div>

              <div className='overflow-hidden'>
                <mo.h2 variants={element} className="pb-2">Company</mo.h2>
              </div>

              <div className='overflow-hidden'>
                <mo.h2 variants={element} className="pb-2">2022</mo.h2>
              </div>

            </mo.div>

            <div>
              <h3>What would you do if you weren’t afraid?</h3>
              <h3>Quality means doing it right when no one is looking.</h3>
              <h3>Take risks. Failure is a stepping stone to success</h3>
            </div>

          </div>

      </main>

      
    </mo.div>
  )
}
